### ISSUE TITLE
ALDEx2 clr coerce.data error

### ISSUE THREAD

**Issue by vmaffei** [ggloor/ALDEx_bioc#20] opened 2019-11-09 20:56 UTC
When running ```aldex.clr``` in version 1.18, coerce.data gives the error

`Error in coerce.data(reads, conds) :
  mismatch between number of samples and condition vector`

despite reads and conds having equivalent number of samples.  I get the same error when running a vignette sample

```R 
covariates <- data.frame("A" = sample(0:1, 14, replace = TRUE), "B" = c(rep(0, 7), rep(1, 7)))
mm <- model.matrix(~ A + B, covariates)
x <- aldex.clr(selex, mm, mc.samples=8, denom="all")
```
```
Error in coerce.data(reads, conds) :
  mismatch between number of samples and condition vector
```
Looking inside ```coerce.data```, the line

```if (ncol(reads) != length(conds))```

appears to evaluate ```length(conds)``` as the number of matrix items (if conds is a matrix or model matrix) instead of the number of columns. 

Transposing ```mm``` and converting to data.frame fixes the error, but produces a new one
```R
clr <- aldex.clr(selex, as.data.frame(t(mm)), useMC=TRUE)
Error in `[.data.frame`(conds, order(conds)) : undefined columns selected
```

Please let me know if I am missing something!

**Comment by ggloor** [comment] 2019-11-15 21:13
sorry for just getting to this. I am unable to reproduce this behaviour, either by copying or pasting your example above, or using the vignette. 

one possibility, are you attempting to bring the data in as a summarized experiment?
another possibility, is class(mm) a matrix on your system?

**Comment by ggloor** [comment] 2020-07-07 18:32
This behaviour is fixed in v1.20 and above

**Closed by ggloor** 2020-07-07 18:32 UTC

**Comment by abdelrhmannabil** [comment] 2022-12-21 21:42
I have the same error.. what should I do to solve it?

**Comment by ggloor** [comment] 2022-12-21 21:48
If this error is persisting, you need to send me a minimal reproducible code so I can troubleshoot. The error indicates that there is a mismatch between the number of samples in your data and the number of labels in the condition vector

**Comment by bariloa** [comment] 2023-02-15 19:46
Hello, I've managed to solve this by transposing my otu table. It seems R was reading my OTU list as sample list mismatching the numbers with metadata.

**Comment by ggloor** [comment] 2023-02-15 22:36
Awesome
